### PR TITLE
Undasherize

### PR DESCRIPTION
**Pull request by steveklabnik**
r? @ashleygwilliams

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
nope. only the foreign keys need underscores. the others still need dash, for now. :cry: :sob: :crying_cat_face: :fire: :gun: :-1:

**Comment by steveklabnik** [comment]
updated

**Comment by ashleygwilliams** [comment]
it's gonna be OK :8ball: :persevere: :person_with_pouting_face:

**Comment by ashleygwilliams** [comment]
oops i suck you need to update the seeds, i'm sorry

**Pull request merged**
